# Generated by Django 5.2.4 on 2025-08-26 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESPAssists', '0002_entry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='topic',
        ),
        migrations.AlterModelOptions(
            name='entry',
            options={},
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='text',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='date_added',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='entry',
            name='feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='prompt',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
