# Generated by Django 5.2.4 on 2025-08-26 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESPAssists', '0003_remove_entry_topic_alter_entry_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='code',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='entry',
            name='feedback',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='entry',
            name='prompt',
            field=models.TextField(blank=True, default=''),
        ),
    ]
